name: Trigger Jenkins Pipeline

on:
  push:
    branches:
      - main

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest
    steps:
      - name: Send Build Trigger to Jenkins
        run: |
          curl -X POST "https://smee.io/haris-jenkins-automation?EC2_HOST=${{ secrets.EC2_HOST }}&EC2_SSH_KEY=${{ secrets.EC2_SSH_KEY }}&MONGO_URI=${{ secrets.MONGO_URI }}&JWT_SECRET=${{ secrets.JWT_SECRET }}&FRONTEND_ORIGIN=${{ secrets.FRONTEND_ORIGIN }}&EMAIL_USER=${{ secrets.EMAIL_USER }}&EMAIL_PASS=${{ secrets.EMAIL_PASS }}&TWILIO_ACCOUNT_SID=${{ secrets.TWILIO_ACCOUNT_SID }}&TWILIO_AUTH_TOKEN=${{ secrets.TWILIO_AUTH_TOKEN }}&TWILIO_PHONE_NUMBER=${{ secrets.TWILIO_PHONE_NUMBER }}" \
            --user "admin:${{ secrets.JENKINS_API_TOKEN }}"

